import { Inter } from "next/font/google";
import "./globals.css";
import CustomProvider from "@/Redux/Prvider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Umair Body builder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomProvider>
          <Navbar />
          {children}
        </CustomProvider>
      </body>
    </html>
  );
}
